spring:
  datasource:
    url: jdbc:mysql://localhost:3308/conference_db?createDatabaseIfNotExist=true
  kafka:
    producer:
      bootstrap-servers: localhost:9092

axon:
  axonserver:
    servers: localhost:8124

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
