spring:
  datasource:
    url: jdbc:mysql://localhost:3307/keynote_db?createDatabaseIfNotExist=true

axon:
  axonserver:
    servers: localhost:8124
    component-name: ${spring.application.name}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
